[uwsgi]
chdir = /app
module = ecommerce.wsgi:application

processes = 2
threads = 4
enable-threads = true
master = true

socket = /run/uwsgi/django.sock
chmod-socket = 666
chown-socket = www-data:www-data

listen = 1024
buffer-size = 32768
post-buffering = 32768
harakiri = 60
harakiri-verbose = true

die-on-term = true
vacuum = true
single-interpreter = true
need-app = true

disable-logging = true
log-4xx = true
log-5xx = true

uid = www-data
gid = www-data

stats = /run/uwsgi/stats.sock
memory-report = true
