user                 www-data;
worker_processes     auto;
pid                  /run/nginx.pid;
error_log            /var/log/nginx/error.log warn;

events {
    worker_connections 1024;
    use epoll;
    multi_accept on;
}

http {
    server_tokens   on;
    include         /etc/nginx/mime.types;
    default_type    application/octet-stream;
    sendfile        on;
    tcp_nopush      on;
    tcp_nodelay     on;
    keepalive_timeout 65;
    client_max_body_size 50M;

    access_log /var/log/nginx/access.log;

    upstream django_uwsgi {
        server 127.0.0.1:3031;
    }

    server {
        listen      8081 default_server;
        server_name _;
        charset     utf-8;

        location /static/ {
            alias /app/staticfiles/;
            access_log off;
            expires 7d;
        }

        location = /healthz {
            access_log off;
            return 200 "ok\n";
        }

        location / {
            include       /etc/nginx/uwsgi_params;
            uwsgi_pass    django_uwsgi;
            uwsgi_read_timeout    60s;
            uwsgi_send_timeout    60s;
            uwsgi_connect_timeout 5s;
        }
    }
}
